const { Octokit } = require('octokit');
const simpleGit = require('simple-git');
const fs = require('fs');
const path = require('path');

async function createDraftPR(event, project, analysis) {
  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
  
  let owner = 'test';
  let repo = 'repo';
  if (project.github_repo_url) {
    const urlParts = project.github_repo_url.replace('https://github.com/', '').split('/');
    if (urlParts.length >= 2) {
      owner = urlParts[0];
      repo = urlParts[1].replace('.git', '');
    }
  }
  
  const branchName = 'codewatch-fix/' + event.id;
  const git = simpleGit(process.cwd());
  
  try {
    await git.checkoutLocalBranch(branchName);
    const patchPath = path.join(process.cwd(), 'fix-' + event.id + '.patch');
    fs.writeFileSync(patchPath, analysis.suggested_fix_diff || '');
    
    try {
       await git.raw(['apply', patchPath]);
    } catch(e) {
       console.error('Failed to apply patch cleanly');
    }
    
    await git.add('.');
    await git.commit('Fix: ' + event.error_message + '\n\nGenerated by CodeWatch AI');
    
    if (process.env.GITHUB_TOKEN) {
      await git.push(['-u', 'origin', branchName]);
      const pr = await octokit.rest.pulls.create({
        owner,
        repo,
        title: '[CodeWatch] Fix for: ' + event.error_message,
        head: branchName,
        base: 'master',
        body: '### Root Cause Analysis\n\n' + analysis.root_cause_summary + '\n\n*Generated by ' + analysis.llm_model_used + '*',
        draft: true
      });
      return pr.data.html_url;
    }
    
    return 'https://github.com/' + owner + '/' + repo + '/compare/master...' + branchName;
  } catch(e) {
    console.error('PR creation error:', e);
    throw e;
  } finally {
    try { fs.unlinkSync(path.join(process.cwd(), 'fix-' + event.id + '.patch')); } catch(e){}
    await git.checkout('master').catch(()=>{});
  }
}

module.exports = { createDraftPR };
